#pragma once

enum TileType
{
	TILE_TYPE_MINE = -1,
	TILE_TYPE_NONE,
	TILE_TYPE_ONE_NEARBY_MINE,
	TILE_TYPE_TWO_NEARBY_MINES,
	TILE_TYPE_THREE_NEARBY_MINES,
	TILE_TYPE_FOUR_NEARBY_MINES,
	TILE_TYPE_FIVE_NEARBY_MINES,
	TILE_TYPE_SIX_NEARBY_MINES,
	TILE_TYPE_SEVEN_NEARBY_MINES,
	TILE_TYPE_EIGHT_NEARBY_MINES,
};
