#pragma once

enum TileType
{
	TILE_TYPE_BOMB = -1,
	TILE_TYPE_NONE,
	TILE_TYPE_ONE_NEARBY_BOMB,
	TILE_TYPE_TWO_NEARBY_BOMBS,
	TILE_TYPE_THREE_NEARBY_BOMBS,
	TILE_TYPE_FOUR_NEARBY_BOMBS,
	TILE_TYPE_FIVE_NEARBY_BOMBS,
	TILE_TYPE_SIX_NEARBY_BOMBS,
	TILE_TYPE_SEVEN_NEARBY_BOMBS,
	TILE_TYPE_EIGHT_NEARBY_BOMBS,
};
